env:
  es6: true
  node: true
plugins:
  - prettier
extends:
  - eslint:recommended
  - prettier
rules:
  prettier/prettier: error

overrides:
  -
    files: "__tests__/**/*.js"
    env:
      jest: true
